### ISSUE TITLE
Small font size

### ISSUE THREAD

**Issue by charraeus** [wiesty/MMM-MVVWiesty#2]
The font size seems to be very small... See attached screenshot.
Viele Grüße, Christian

![IMG_4908](https://github.com/wiesty/MMM-MVVWiesty/assets/38609969/69190136-2e4a-4c92-9324-795984cbe442)

**Comment by wiesty** [comment]
Okay, 
thanks will add another configuration option :) 

Grüße Wiesty :)

**Comment by wiesty** [comment]
Hi @charraeus 

could you check if the font size is okay now? I have increased the value. (Just reclone the module) 
If it is still to small the fontsize can be changed in the css in Line 4 and 5. 

Thanks & greetings :)

**Comment by charraeus** [comment]
Hi @wiesty 

the font size is now perfect. Thank's a lot.
