### ISSUE TITLE
No data by MVG. Check station id.undefined

### ISSUE THREAD

**Issue by SiDuMo1** [wiesty/MMM-MVVWiesty#3]
I get the error message in the title displayed on the mirror.
Steps I've taken so far:
- re-installing the module
- using the standard config from the description

Anybody with the same issue?
I really like the module and would love to have it working again :)

Best, Simon

**Comment by wiesty** [comment]
Hey @SiDuMo1,

great news, you are using my old module. https://github.com/wiesty/MMM-MVGWiesty/blob/master/MMM-MVGWiesty.js if you look on line 91 that should be the error you have. MVG randomly shut down their api, but I found a workaround. You have to delete the MMM-MV**G**Wiesty and (re)install MMM-MV**V**Wiesty. The config is slightly different, so have a look in the readme to lookup your stopid. 


Links:

MMM-MVGWiesty (old): https://github.com/wiesty/MMM-MVGWiesty

MMM-MVVWiesty (new): https://github.com/wiesty/MMM-MVVWiesty


If you are still facing issues let me know :) 

Cheers

**Comment by SiDuMo1** [comment]
Awesome, now it works again :) Thanks!
