### ISSUE TITLE
Add example image directly to the repository

### ISSUE THREAD

**Issue by KristjanESPERANTO** [wiesty/MMM-MVVWiesty#4]
Can you add the example image directly to the repository? For example as `screenshot.png` or `example.png` in any folder :slightly_smiling_face: 

This would have the advantage that the image would be displayed in [the module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I am working on.

**Comment by wiesty** [comment]
Done img @ assets/example.png

**Comment by KristjanESPERANTO** [comment]
Thanks! Now it looks nice in the list :slightly_smiling_face:
